name: Publish Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - uses: actions/checkout@v3.5.3
      - name: Set up JDK 17
        uses: actions/setup-java@v3.11.0
        with:
          java-version: 17
          distribution: adopt
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

        # Build and publish
      - name: Build with Gradle
        run: ./gradlew shadowJar

      - name: Publish to Modrinth
        run: ./gradlew modrinth
        env:
          modrinthApiKey: ${{ secrets.MODRINTH_TOKEN }}
          modrinthChangelog: ${{ github.event.release.body }}

      - name: Publish to Hangar
        run: ./gradlew publishPluginPublicationToHangar
        env:
          hangarApiKey: ${{ secrets.HANGAR_TOKEN }}
          hangarChangelog: ${{ github.event.release.body }}

        # Attach output to release
      - name: Get artifact version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Attach artifact to release
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/libs/instantrestock_${{ steps.get_version.outputs.VERSION }}.jar
          asset_name: instantrestock_${{ steps.get_version.outputs.VERSION }}.jar
          asset_content_type: application/java-archive
